main_rack_A:
  x_origin: 53
  #y_origin: 137
  y_origin: 135
  z_origin: -48.18
  #z_origin: -45.9
  num_x: 3
  num_y: 1
  x_offset: 80
  y_offset: 0

washing_station:
  x_origin: 275
  y_origin: 137
  z_origin: -35
  num_x: 1
  num_y: 3
  x_offset: 0
  y_offset: 80